config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}
  get 'index' => 'welcome#index', as: 'index'
  get 'about' => 'welcome#about', as: 'about'
  get 'participants' => 'welcome#participants', as: 'participants'
  

 root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  protected
  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:username,:email,:password,:password_confirmation)}
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	def new
		super
	end
	def create
		super		
	end
	def update
		super
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index  	
  end
  def about  	
  end
  def participants  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pioneros UCaldas (Nombre por definir)</title>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
        <div class="bs-example">
            <nav role="navigation" class="navbar navbar-default">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="#" class="navbar-brand">Aquí el Logo</a>
                </div>
                <!-- Collection of nav links and other content for toggling -->
                <div id="navbarCollapse" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active">
                            <%= link_to "Inicio", index_path %>
                        </li>
                        <li>
                            <%= link_to "Quienes Somos", about_path %>
                        </li>
                        <li>
                            <%= link_to "Participantes", participants_path %>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <% if user_signed_in? %>
                            <li>
                                <a href="">                                    
                                    <%= current_user.username %>
                                </a>
                            </li>
                            <li>
                                <%= link_to "SignOut", destroy_user_session_path, method: :delete %>
                            </li>
                        <%else%>
                            <li>
                                <%= link_to "LogIn", new_user_session_path %>
                            </li>
                            <li>
                                <%= link_to "SignUp", new_user_registration_path %>
                            </li>
                        <%end%>                        
                    </ul>
                </div>
            </nav>
        </div>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>    
    <%= yield %>
</body>
</html>

app/views/welcome/about.html.erb
<blockquote>
	<p>
		En un lugar de la mancha de cuyo nombre no quiero acordarme
	</p>
	<p>
	Somos un grupo pero quiero amar a todos de personas que tiene como meta lograr conformar un fuerte equipo de trabajo, un ambiente de camaradería par trabajar y con estas bases, lograr grandes objetivos.
	</p>
</blockquote>

app/views/welcome/index.html.erb
<blockquote>	
	<h1>Sitio en construcción</h1>
</blockquote>

app/views/welcome/participants.html.erb
<section class="col-xs-12" style="margin-left:8%">
	<div class="col-xs-4 dl-horizontal">
		<%= image_tag("Catalina.jpg", :alt => "rss feed", :class => "img-circle img-responsive") %>
		<br>Catalina Grajales
	</div>
	<div class="col-xs-4 dl-horizontal">
		<%= image_tag("Cristian.jpg", :alt => "rss feed", :class => "img-circle img-responsive") %>
		<br>Cristian Castro
	</div>
	<div class="col-xs-4 dl-horizontal">
		<%= image_tag("CamiloAlvarez.jpg", :alt => "rss feed", :class => "img-circle img-responsive") %>
		<br>
		<div class="center-block">
			Camilo Alvarez
		</div>
		
	</div>
	
</section>